### ISSUE TITLE
Mail / SMS gateway example

### ISSUE THREAD

**Issue by kblumenau** [ozzi-/EasyVisit#1]
Hi, is this project still active? I like the things a have seen... so would be nice

Are there examples on how to implement the mail or sms gateway option?

Thanks and Best Regards,

Karsten

**Comment by ozzi-** [comment]
Hi @kblumenau 
It is alive, but currently due to other projects not very active.
An example for SMS can be found here:
https://github.com/ozzi-/EasyVisit/blob/master/sms.php - please let me know if you have specific questions.
PHP has inbuilt methods for mail delivery, so that should be rather easy.

Cheers

**Comment by kblumenau** [comment]
Thanks for the quick answer! I will try to recover some php from my past trying to understand...

I have some other requirements, maybe you have that already in your list or someone else has it:
- guests should be able to input Mail address and Telephone number - for Corona this even could be a must (to contact them afterwards in case...)
- guests should be able to checkin using a dedicated webpage (on whatever device) using a special link (provided i.e. via QR code)
- signature should be optional (config option to surpress that page)
- self-service checkout (request) with a token special to that user

By the way, it seems that the name easyvisit is already taken for something else, or do i misunderstand?

**Comment by ozzi-** [comment]
-  guests should be able to input Mail address and Telephone number - for Corona this even could be a must (to contact them afterwards in case...)

this could be added fairly simply,

-     guests should be able to checkin using a dedicated webpage (on whatever device) using a special link (provided i.e. via QR code)

requires some work

-     signature should be optional (config option to surpress that page)

is already possible

-     self-service checkout (request) with a token special to that user

requires some work

as you can see, easyvisit was designed not as self service
